version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  client:
    build: ./app     
    depends_on:
      - db
    networks:
      - appnet
    stdin_open: true
    tty: true

volumes:
  pgdata:

networks:
  appnet:
